name: flutter_quizlet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_storage: ^12.4.5
  provider: ^6.1.5
  flutter_svg: ^2.1.0
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/google.svg
    - assets/images/facebook.svg

    - assets/animations/welcome.json