// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMVjRmOOIj6BKL2BPga4NMUpPhgjMcrQw',
    appId: '1:711173234816:web:8d34d4b1f0db9a2fbf0665',
    messagingSenderId: '711173234816',
    projectId: 'shop-50072',
    authDomain: 'shop-50072.firebaseapp.com',
    storageBucket: 'shop-50072.appspot.com',
    measurementId: 'G-MXQNPERL4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi5_iFpwwERpTVEOk3Eoz8T-Hh_ODwLe0',
    appId: '1:711173234816:android:e259e3fc2b37d0ccbf0665',
    messagingSenderId: '711173234816',
    projectId: 'shop-50072',
    storageBucket: 'shop-50072.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTEJHNxxmp5ImH6I7G637DGQksFOGxZyU',
    appId: '1:711173234816:ios:8254891c98b9ce76bf0665',
    messagingSenderId: '711173234816',
    projectId: 'shop-50072',
    storageBucket: 'shop-50072.appspot.com',
    iosClientId: '711173234816-8en8u7v3dm7k7k965hiug3d6jqtrv962.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterQuizlet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTEJHNxxmp5ImH6I7G637DGQksFOGxZyU',
    appId: '1:711173234816:ios:8254891c98b9ce76bf0665',
    messagingSenderId: '711173234816',
    projectId: 'shop-50072',
    storageBucket: 'shop-50072.appspot.com',
    iosClientId: '711173234816-8en8u7v3dm7k7k965hiug3d6jqtrv962.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterQuizlet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMVjRmOOIj6BKL2BPga4NMUpPhgjMcrQw',
    appId: '1:711173234816:web:a5fa8958e480b4fdbf0665',
    messagingSenderId: '711173234816',
    projectId: 'shop-50072',
    authDomain: 'shop-50072.firebaseapp.com',
    storageBucket: 'shop-50072.appspot.com',
    measurementId: 'G-X4E0TGFCKS',
  );
}
